# Generated by Django 4.2.30 on 2026-06-01 02:07

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpreendimentoEolico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_parque', models.CharField(blank=True, max_length=255, null=True)),
                ('status_operacional', models.CharField(blank=True, max_length=100, null=True)),
                ('capacidade_mw', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('data_operacao', models.DateField(blank=True, null=True)),
                ('fonte_dado', models.CharField(blank=True, max_length=100, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=31984)),
            ],
        ),
        migrations.CreateModel(
            name='EmpreendimentoSolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_usina', models.CharField(blank=True, max_length=255, null=True)),
                ('status_operacional', models.CharField(blank=True, max_length=100, null=True)),
                ('capacidade_mw', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('data_operacao', models.DateField(blank=True, null=True)),
                ('fonte_dado', models.CharField(blank=True, max_length=100, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=31984)),
            ],
        ),
    ]
