# Generated by Django 4.2.30 on 2026-06-23 02:25

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empreendimentoeolico',
            options={'verbose_name': 'Empreendimento Eólico', 'verbose_name_plural': 'Empreendimentos Eólicos'},
        ),
        migrations.AlterField(
            model_name='empreendimentoeolico',
            name='capacidade_mw',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Capacidade (MW)'),
        ),
        migrations.AlterField(
            model_name='empreendimentoeolico',
            name='data_operacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Operação'),
        ),
        migrations.AlterField(
            model_name='empreendimentoeolico',
            name='fonte_dado',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fonte de Dados'),
        ),
        migrations.AlterField(
            model_name='empreendimentoeolico',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(srid=31984, verbose_name='Geometria'),
        ),
        migrations.AlterField(
            model_name='empreendimentoeolico',
            name='nome_parque',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Parque'),
        ),
        migrations.AlterField(
            model_name='empreendimentoeolico',
            name='status_operacional',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Status Operacional'),
        ),
    ]
