# Generated by Django 4.2.30 on 2026-06-23 02:31

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapas', '0002_alter_empreendimentoeolico_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empreendimentosolar',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(srid=31984, verbose_name='Geometria'),
        ),
    ]
