# Generated by Django 4.2.30 on 2026-07-01 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapas', '0003_alter_empreendimentosolar_geom'),
    ]

    operations = [
        migrations.AddField(
            model_name='empreendimentoeolico',
            name='municipio',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Município'),
        ),
        migrations.AddField(
            model_name='empreendimentosolar',
            name='municipio',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Município'),
        ),
    ]
