# Generated by Django 4.2.30 on 2026-07-02 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapas', '0004_empreendimentoeolico_municipio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empreendimentoeolico',
            name='fonte',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fonte'),
        ),
        migrations.AddField(
            model_name='empreendimentoeolico',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='empreendimentosolar',
            name='fonte',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fonte'),
        ),
        migrations.AddField(
            model_name='empreendimentosolar',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Status'),
        ),
    ]
