# Generated by Django 4.2.30 on 2026-07-11 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapas', '0005_empreendimentoeolico_fonte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empreendimentoeolico',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Última Atualização'),
        ),
    ]
